[platformio]
src_dir = firmware/src
lib_dir = firmware/lib
test_dir = firmware/test

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
build_flags = -DUSB_MIDI_AUDIO_SERIAL -DAUDIO_BLOCK_SAMPLES=128 -std=gnu++17 -O2
monitor_speed = 115200
upload_port = /dev/cu.usbmodem150385601
upload_protocol = teensy-cli
